openapi: 3.0.0
info:
  title: Admin Panel API
  version: 1.0.0
  description: >
    API для управления товарами (создание, получение списка, обновление и удаление).
servers:
  - url: http://localhost:4000

paths:
  /products:
    get:
      summary: Получить список товаров
      description: Возвращает массив объектов Product
      responses:
        '200':
          description: Список товаров
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      summary: Создать новый товар
      description: Добавляет новый товар в систему
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductInput'
      responses:
        '201':
          description: Товар успешно создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'

  /products/{id}:
    get:
      summary: Получить товар по ID
      description: Возвращает товар с указанным ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Найденный товар
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Товар не найден
    put:
      summary: Обновить товар по ID
      description: Изменяет поля существующего товара
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductInput'
      responses:
        '200':
          description: Товар успешно обновлён
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Товар не найден
    delete:
      summary: Удалить товар по ID
      description: Удаляет товар из системы
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Товар успешно удалён
        '404':
          description: Товар не найден

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "Товар 1"
        price:
          type: number
          example: 100.0
        description:
          type: string
          example: "Любви, надежды, тихой славы Недолго нежил нас обман, Исчезли юные забавы, Как сон, как утренний туман;"
        categories:
          type: array
          items:
            type: string
          example: ["Книги", "Пушкин"]

    ProductInput:
      type: object
      properties:
        name:
          type: string
          example: "Товар 2"
        price:
          type: number
          example: 100.0
        description:
          type: string
          example: "Но в нас горит еще желанье, Под гнетом власти роковой Нетерпеливою душой Отчизны внемлем призыванье."
        categories:
          type: array
          items:
            type: string
          example: ["Одежда", "Пушкин"]
