version: '3.8'

services:
  backend1:
    build: .
    networks:
      - appnet

  backend2:
    build: .
    networks:
      - appnet

  backend3:
    build: .
    networks:
      - appnet

  # nginx
  lb:
    image: nginx:alpine
    depends_on:
      - backend1
      - backend2
      - backend3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3000:80"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
